site_name: FJBoy's Docs
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

plugins:
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://unpkg.com/mermaid@8.13.8/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/config.js
  # - javascripts/mathjax.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css
