site_name: FJBoy's Docs
repo_url: https://github.com/fjoby-light-fs
copyright: Copyright &copy; 2021 - 2030 fjboy
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

plugins:
  - mermaid2
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - https://unpkg.com/mermaid@8.13.8/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/config.js
  # - javascripts/mathjax.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fjboy
      name: squidfunk on github
